# Configuration file for Multimodal Market Analyst AI System

# Database Settings
chroma_db:
  collection_name: "financial_data"
  host: "localhost"
  port: 8000

# Analysis Settings
analysis_period: "1y"  # Options: "3m", "6m", "1y", "5y"
default_company: "Microsoft"

# Forecasting Models
forecasting:
  model: "prophet"  # Options: "prophet", "arima"
  confidence_interval: 0.95

# Visualization Settings
visualization:
  theme: "plotly_dark"
  interactive: true

# Logging
logging:
  level: "INFO"
  log_to_file: true
  log_file: "logs/system.log"

# API Settings
api:
  host: "0.0.0.0"
  port: 8080

